package csci567.squeez;

public enum Status {
    OK,
    DOES_NOT_EXIST,
    NAME_TAKEN,
    NOT_DIRECTORY,
    NOT_FILE,
    COULD_NOT_DELETE,
    COULD_NOT_RENAME,
    COULD_NOT_COPY,
    COULD_NOT_UNZIP,
    COULD_NOT_ZIP,
    DESTINATION_NOT_DIRECTORY
}
